module:
  mounts:
    - source: templates
      target: layouts/_default
    - source: func
      target: layouts/partials/func
outputFormats:
  netlifycms_dash:
    baseName: tnd-cms/jan
    mediatype: text/html
    notAlternative: true
  netlifycms_config_debug:
    baseName: config
    isPlainText: true
    mediatype: text/plain
    notAlternative: true
  netlifycms_config:
    baseName: tnd-cms/config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: true
mediaTypes:
  application/yaml:
    suffixes:
    - yml