module:
  mounts:
    - source: templates
      target: layouts/netlifycms
    - source: func
      target: layouts/partials/tnd-netlifycms
    - source: partials
      target: layouts/partials/tnd-netlifycms
outputFormats:
  netlifycms_debug:
    baseName: config
    isPlainText: true
    mediatype: text/plain
    notAlternative: false
  netlifycms_config:
    baseName: config
    isPlainText: true
    mediatype: application/yaml
    notAlternative: false
mediaTypes:
  application/yaml:
    suffixes:
    - yml